### ISSUE TITLE
Other hardware abstraction layers in python

### ISSUE THREAD

**Issue by edbarnard** [python-data-acquisition/meta#12]
So we don't reinvent the wheel, perhaps we should record what projects are out there that have similar goals or subsets of what we are trying to do here.

**Comment by edbarnard** [comment]
**Ophyd**

Part of the bluesky project design at particle accelerators. Ophyd provides a hardware abstraction that is typically on top of distributed controls for accelerators, but can be used more generally.

https://blueskyproject.io/ophyd/

**Comment by HazenBabcock** [comment]
I think we were attempting to create a record [here](https://github.com/python-data-acquisition/meta/blob/master/existing_packages.md).

**Comment by edbarnard** [comment]
Thanks I'll move the write up to the appropriate page
